// config/client.ts
// ============================================================================
// CLIENT CONFIGURATION - Single Source of Truth
//
// This file is generated by the Setup Wizard. All other files reference
// these values via clientConfig.
//
// DO NOT hardcode client-specific values elsewhere - always use clientConfig
// ============================================================================

export const clientConfig = {
  // ==========================================================================
  // PLATFORM TYPE (Determines core functionality)
  // Options: 'impact_investor' | 'commercial_investor' | 'family_office' | 'founder_service_provider'
  // ==========================================================================
  platformType: 'impact_investor' as 'impact_investor' | 'commercial_investor' | 'family_office' | 'founder_service_provider',
  platformMode: 'screening' as 'screening' | 'coaching',

  // ==========================================================================
  // COMPANY INFORMATION
  // ==========================================================================
  company: {
    name: "RaiseReady Impact",
    legalName: "Global Buildtech Australia Pty Ltd",
    tagline: "AI-Powered Pitch Coaching for Impact Founders",
    description: "We help impact founders perfect their pitch and connect with aligned investors who share their vision for positive change.",

    // URLs
    website: "https://raiseready-impact.vercel.app",
    platformUrl: "https://raiseready-impact.vercel.app",

    // Contact
    supportEmail: "support@raiseready.com",
    salesEmail: "dennis@corporate-ai-solutions.com",

    // Social
    social: {
      linkedin: "https://linkedin.com/company/raiseready",
      twitter: "https://twitter.com/raiseready",
      youtube: "https://youtube.com/@raiseready",
    },

    // Logo paths (relative to /public)
    logo: {
      light: "/logo-light.svg",
      dark: "/logo-dark.svg",
      favicon: "/favicon.ico",
    },
  },

  // ==========================================================================
  // ADMIN USER (Primary Contact)
  // ==========================================================================
  admin: {
    firstName: "Dennis",
    lastName: "Villanueva",
    email: "dennis@corporate-ai-solutions.com",
    phone: "+61 402 612 471",
    position: "CEO",
    linkedIn: "https://linkedin.com/in/dennisvillanueva",
  },

  // ==========================================================================
  // OFFICE LOCATIONS
  // ==========================================================================
  offices: [
    {
      city: "Brisbane",
      country: "Australia",
      address: "Brisbane, Queensland",
      phone: "+61 402 612 471",
      isPrimary: true,
    },
  ],

  // ==========================================================================
  // THEME & BRANDING
  // ==========================================================================
  theme: {
    mode: "dark" as "dark" | "light",
    colors: {
      primary: "#8B5CF6",      // Purple - main brand color
      primaryHover: "#7C3AED",
      accent: "#10B981",       // Emerald - impact/success color
      accentHover: "#059669",
      background: "#0F172A",   // Dark mode background
      surface: "#1E293B",      // Card/surface background
      text: "#F8FAFC",
      textMuted: "#94A3B8",
      border: "#334155",
      gradient: { from: "#8B5CF6", via: "#0F172A", to: "#10B981" },
      success: "#22C55E",
      warning: "#F59E0B",
      error: "#EF4444",
    },
    gradients: {
      hero: "from-purple-600 via-violet-700 to-indigo-800",
      button: "from-purple-500 to-violet-600",
      card: "from-slate-800 to-slate-900",
    },
    fonts: {
      heading: "Inter",
      body: "Inter",
    },
    borderRadius: "0.5rem",
  },

  // ==========================================================================
  // LANDING PAGE CONTENT
  // ==========================================================================
  landing: {
    hero: {
      headline: "Perfect Your Impact Pitch",
      subHeadline: "AI-powered coaching to help impact founders tell their story, prove their thesis, and connect with aligned investors.",
      ctaText: "Start Your Pitch",
      ctaLink: "/signup/founder",
      secondaryCtaText: "For Investors",
      secondaryCtaLink: "/signup/investor",
    },
    stats: [
      { value: "500+", label: "Founders Coached" },
      { value: "$50M+", label: "Impact Capital Raised" },
      { value: "85%", label: "Pitch Improvement" },
      { value: "17", label: "SDGs Addressed" },
    ],
    valueProps: [
      {
        icon: "Brain",
        title: "AI Pitch Analysis",
        description: "Get instant feedback on your pitch deck using our proprietary RealChange Impact Index.",
      },
      {
        icon: "Target",
        title: "SDG Alignment Scoring",
        description: "Quantify your impact across all 17 UN Sustainable Development Goals.",
      },
      {
        icon: "TrendingUp",
        title: "Blended Returns",
        description: "Show investors the true value with financial + impact returns calculated together.",
      },
      {
        icon: "Mic",
        title: "Voice Coaching",
        description: "Practice your pitch with AI and get real-time feedback on delivery and persuasion.",
      },
      {
        icon: "Users",
        title: "Investor Matching",
        description: "Connect with impact investors whose thesis aligns with your SDG focus.",
      },
      {
        icon: "Shield",
        title: "Investor Ready Score",
        description: "Know exactly where you stand before you pitch. Track progress over time.",
      },
    ],
    howItWorks: [
      {
        step: "1",
        title: "Submit Your Pitch",
        description: "Upload your deck and answer questions about your impact thesis and business model.",
      },
      {
        step: "2",
        title: "Get AI Coaching",
        description: "Receive detailed analysis across 12 dimensions including SDG alignment and impact measurability.",
      },
      {
        step: "3",
        title: "Practice & Improve",
        description: "Use voice coaching to practice delivery. Watch your scores improve over time.",
      },
      {
        step: "4",
        title: "Connect with Investors",
        description: "When ready, get matched with impact investors looking for founders like you.",
      },
    ],
  },

  // ==========================================================================
  // INVESTMENT THESIS (Seeded from website, refined by admin)
  // ==========================================================================
  thesis: {
    focusAreas: [
      "Climate Tech & Clean Energy",
      "Financial Inclusion",
      "Healthcare Access",
      "Education Technology",
      "Sustainable Agriculture",
      "Circular Economy",
    ],
    sectors: [
      "CleanTech",
      "FinTech",
      "HealthTech",
      "EdTech",
      "AgTech",
      "Impact SaaS",
    ],
    stages: [
      "Pre-Seed",
      "Seed",
      "Series A",
    ],
    geographies: [
      "Global",
      "Asia-Pacific",
      "North America",
      "Europe",
    ],
    ticketSize: {
      min: "$100K",
      max: "$2M",
      sweet: "$250K - $1M",
    },
    philosophy: "We believe the best investments create both financial returns and measurable positive impact. Our RealChange Impact Index quantifies social and environmental outcomes in USD equivalents, enabling true comparison of blended returns.",
    idealFounder: "Mission-driven founders building scalable solutions to global challenges, with clear theory of change and measurable impact metrics.",
    dealBreakers: [
      "No clear impact thesis",
      "Unmeasurable outcomes",
      "Impact washing",
      "Misaligned values",
    ],
  },

  // ==========================================================================
  // AI COACHING CONFIGURATION
  // ==========================================================================
  coaching: {
    coachName: "Maya",
    coachPersonality: "A supportive but direct pitch coach with deep experience in impact investing. Maya helps founders articulate their impact thesis clearly and practice their delivery with confidence.",
    voiceAgentId: "", // ElevenLabs agent ID (set via env var)

    scoringFocus: "impact" as "storytelling" | "impact" | "growth",

    scoringCriteria: [
      { key: "problem_clarity", label: "Problem Clarity", weight: 0.10 },
      { key: "solution_clarity", label: "Solution Clarity", weight: 0.10 },
      { key: "market_opportunity", label: "Market Opportunity", weight: 0.08 },
      { key: "business_model", label: "Business Model", weight: 0.10 },
      { key: "traction", label: "Traction & Validation", weight: 0.08 },
      { key: "team", label: "Team & Execution", weight: 0.08 },
      { key: "financials", label: "Financial Projections", weight: 0.06 },
      { key: "ask_clarity", label: "Ask & Use of Funds", weight: 0.06 },
      { key: "sdg_alignment", label: "SDG Alignment", weight: 0.12 },
      { key: "impact_measurability", label: "Impact Measurability", weight: 0.12 },
      { key: "theory_of_change", label: "Theory of Change", weight: 0.05 },
      { key: "storytelling", label: "Storytelling", weight: 0.05 },
    ],

    // Welcome messages for different coaching modes
    welcomeMessages: {
      discovery: `Welcome to RaiseReady Impact Story Discovery! I'm Maya, and I'll help you uncover the compelling narrative behind your impact startup.`,
      practice: `Ready to practice your impact pitch? I'm Maya, and I'll give you real-time feedback to sharpen your delivery and impact thesis.`,
      simulation: `Let's simulate an impact investor meeting. I'll play the role of different investor types to prepare you for the real thing.`,
    },
  },

  // ==========================================================================
  // PLATFORM SETTINGS
  // ==========================================================================
  platform: {
    // URL prefix for portal routes (middleware rewrites to /portal/)
    urlPrefix: "portal",

    // Admin role name in database
    adminRole: "portal_admin",

    // Feature toggles
    features: {
      voiceCoaching: true,
      investorMatching: true,
      deckVersioning: true,
      teamMembers: false,
      analytics: true,
      apiAccess: false,
      sdgScoring: true,
      impactMetrics: true,
      blendedReturns: true,
    },

    // Founder journey steps
    founderJourney: [
      { id: "upload", label: "Upload Deck", icon: "Upload" },
      { id: "profile", label: "Complete Profile", icon: "User" },
      { id: "discovery", label: "Story Discovery", icon: "MessageSquare" },
      { id: "refine", label: "Refine Materials", icon: "FileEdit" },
      { id: "practice", label: "Practice Pitch", icon: "Mic" },
    ],

    // Readiness levels
    readinessLevels: [
      { key: "not-ready", label: "Not Ready", minScore: 0, color: "red" },
      { key: "needs-work", label: "Needs Work", minScore: 40, color: "orange" },
      { key: "almost-ready", label: "Almost Ready", minScore: 60, color: "yellow" },
      { key: "investor-ready", label: "Investor Ready", minScore: 80, color: "green" },
    ],

    // Auto-reply template for founder submissions
    autoReplyTemplate: `
Thank you for submitting your pitch to RaiseReady Impact!

We've received your deck and our AI coaching system is analyzing it now. 
You'll receive your initial feedback within 24 hours.

In the meantime, you can:
- Complete your founder profile
- Start your Story Discovery session with Maya
- Practice your pitch with our AI coach

Best regards,
The RaiseReady Impact Team
    `,
  },

  // ==========================================================================
  // FOOTER CONTENT
  // ==========================================================================
  footer: {
    description: "AI-powered pitch coaching for impact founders. Perfect your pitch, prove your impact, connect with aligned investors.",
    serviceLinks: [
      { label: "For Founders", href: "/signup/founder" },
      { label: "For Investors", href: "/signup/investor" },
      { label: "Pricing", href: "/pricing" },
    ],
    companyLinks: [
      { label: "About", href: "/about" },
      { label: "How It Works", href: "/#how-it-works" },
      { label: "Contact", href: "/contact" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/privacy" },
      { label: "Terms of Service", href: "/terms" },
    ],
    copyright: `© {year} RaiseReady Impact. Powered by Global Buildtech Australia.`,
  },

  // ==========================================================================
  // LEGAL & COMPLIANCE
  // ==========================================================================
  legal: {
    privacyUrl: "/privacy",
    termsUrl: "/terms",
    copyrightYear: new Date().getFullYear(),
    complianceRegions: ["GDPR", "CCPA"],
  },

  // ==========================================================================
  // EXTERNAL SERVICE IDS (Populated during setup)
  // ==========================================================================
  services: {
    supabase: {
      projectId: "",
      url: "",
      // Keys stored in env vars, not here
    },
    vercel: {
      projectId: "",
      deploymentUrl: "",
    },
    elevenlabs: {
      agentId: "",
      voiceId: "",
    },
    anthropic: {
      // Key stored in env vars
    },
  },
};

// ==========================================================================
// HELPER FUNCTIONS
// ==========================================================================

/** Get company name */
export const getCompanyName = () => clientConfig.company.name;

/** Get admin full name */
export const getAdminName = () =>
  `${clientConfig.admin.firstName} ${clientConfig.admin.lastName}`;

/** Get admin role */
export const getAdminRole = () => clientConfig.platform.adminRole;

/** Get URL prefix */
export const getUrlPrefix = () => clientConfig.platform.urlPrefix;

/** Get coach name */
export const getCoachName = () => clientConfig.coaching.coachName;

/** Get portal route */
export const getPortalRoute = (path: string) =>
  `/${clientConfig.platform.urlPrefix}${path}`;

/** Get themed color */
export const getThemeColor = (color: keyof typeof clientConfig.theme.colors) =>
  clientConfig.theme.colors[color];

/** Replace template variables in text */
export const replaceTemplateVars = (text: string): string => {
  return text
    .replace(/{company}/g, clientConfig.company.name)
    .replace(/{coach}/g, clientConfig.coaching.coachName)
    .replace(/{year}/g, String(clientConfig.legal.copyrightYear))
    .replace(/{admin}/g, getAdminName())
    .replace(/{email}/g, clientConfig.company.supportEmail);
};

/** Check if feature is enabled */
export const isFeatureEnabled = (feature: keyof typeof clientConfig.platform.features) =>
  clientConfig.platform.features[feature];

// ==========================================================================
// PLATFORM TYPE HELPERS
// ==========================================================================

/** Get current platform type */
export const getPlatformType = () => clientConfig.platformType;

/** Check if platform is a service provider (coaching only, no investor matching) */
export const isServiceProvider = () => clientConfig.platformType === 'founder_service_provider';

/** Check if platform is an impact investor */
export const isImpactInvestor = () => clientConfig.platformType === 'impact_investor';

/** Check if platform is a family office */
export const isFamilyOffice = () => clientConfig.platformType === 'family_office';

/** Check if platform is a commercial investor */
export const isCommercialInvestor = () => clientConfig.platformType === 'commercial_investor';

/** Check if investor matching is available (not for service providers) */
export const hasInvestorMatching = () =>
  clientConfig.platform.features.investorMatching && !isServiceProvider();

/** Check if SDG scoring is relevant */
export const hasSDGScoring = () =>
  isImpactInvestor() && clientConfig.platform.features.sdgScoring;

/** Check if platform is in screening mode (vs coaching only) */
export const isScreeningMode = () => clientConfig.platformMode === 'screening';

/** Check if platform is in coaching mode (no investor matching) */
export const isCoachingMode = () => clientConfig.platformMode === 'coaching';

// Type export for use in other files
export type ClientConfig = typeof clientConfig;